#!/usr/bin/env node

var xml = require("libxmljs"),
    fs = require("fs"),
    path = require("path");

var rawXml = fs.readFileSync("wrappers/mvc/src/Kendo.Mvc/bin/Release/Kendo.Mvc.xml", "utf8");

// Replace <see /> tags with their "cref" attribute value
//
rawXml = rawXml.replace(/<see cref="([^"]*)"\s*\/>/g, function($0, $1){
    // return only the last word of the cref attribute
    return $1.replace(/^.*?(\w+)$/, "$1");
});

var xmlDoc = xml.parseXmlString(rawXml);
var members = xmlDoc.find("//member")

function parseNamespace(namespace) {
    var namespaceRegExp = new RegExp("^T:" + namespace.replace(/\./g, "\\.") + "\\.([^\\.]+)$");
    var types = {};

    members.forEach(function(member) {
        var name = member.attr("name").value().replace(/`\d/, "");
        var type;
        var fullName;
        var shortName;

        if (namespaceRegExp.test(name)) {
            shortName = RegExp.$1;
            fullName = namespace + "." + shortName;

            types[shortName] = type = {};
            type.name = fullName;
            type.methods = [];
            type.properties = [];
            type.summary = parseSummary(member);

            parseMembers(type);
        }
    });

    return types;
}

function parseMembers(type) {
    var namespaceRegExp = new RegExp("^(\w):" + type.name.replace(/\./g, "\\.") + "\\.([^\\.]+)");

    members.forEach(function(member) {
        var name = member.attr("name").value().replace(/`\d/, "");
        var type;
        var kind;
        var fullName;
        var shortName;

        if (namespaceRegExp.test(name)) {
            kind = RegExp.$1;
            shortName = RegExp.$2;
            fullName = namespace + "." + shortName;

            if (kind == "M" && name.indexOf("#ctor") < 0) {
                var method = parseMethod(member);

                method.name = memberName(fullName, name)
                type.methods.push(method);
            }
        }
    });
}

function typeToMarkdown(type) {
    var markdown = "";

    markdown += "---";
    markdown += "\ntitle:" + type.name;
    markdown += "\nslug:aspnetmvc-" + type.name.toLowerCase();
    markdown += "\npublish:true";
    markdown += "\n---";

    markdown += "\n\n# " + type.name;

    if (type.summary) {
        markdown += "\n\n" + type.summary;
    }

    if (type.methods.length) {
        markdown += "\n\n## Methods";

        type.methods.forEach(function(method){
            markdown += emitMethod(method);
        });
    }

    return markdown.trim();
}

function emitMethod(method) {
    var markdown = "";

    markdown += "\n\n### " + method.name;

    if (method.summary) {
        markdown += "\n" + method.summary;
    }

    if (method.examples) {
        markdown += "\n\n#### Example";

        method.examples.forEach(function(example) {
            markdown += emitExample(example);
        })
    }

    if (method.params) {
        var paramTypes = /\(([^\)]*)\)$/.exec(method.name)[1].split(",");

        markdown += "\n\n#### Parameters";

        method.params.forEach(function(param, index) {
            markdown += emitParam(param, paramTypes[index]);
        })
    }

    if (method.returns) {
        markdown += "\n\n#### Returns";
        markdown += "\n" + method.returns;
    }

    return markdown;
}

function emitParam(param, type) {
    var markdown = "";

    markdown += "\n\n##### " + param.name + " `" + type + "`";

    if (param.summary) {
        markdown += "\n" + param.summary;
    }

    return markdown;
}

function emitExample(example) {
    return "\n    " + example.code.replace(/^ {4}/gm, "").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"');
}

function memberName(typeName, name) {
    return name.replace(/\w:/, "").substring(typeName.length + 1);
}

function parseMethod(element) {
    var result = {};

    result.summary = parseSummary(element);

    var params = element.find("param");

    if (params.length) {
        result.params = params.map(parseParam);
    }

    var examples = element.find("example");

    if (examples.length) {
        result.examples = examples.map(parseExample);
    }

    var returns = element.get("returns");

    if (returns) {
        result.returns = text(returns);
    }

    return result;
}

function parseParam(param) {
    return {
       name: param.attr("name").value(),
       summary: text(param)
    };
}

function text(element) {
    return element.text().trim();
}

function parseExample(example) {
    var code = example.get("code");

    return {
       code: code.text().trim()
    }
}

function parseSummary(element) {
   var summary = element.get("summary");

   if (summary) {
        summary = text(summary);

        if (summary) {
           return summary;
        }
   }

   return "";
}

function isEmpty(object) {
    for (var member in object) {
        return false;
    }

    return true;
}

function makePath(/**Array*/ path) {
     path = path.split(/[\\\/]/);
    var make = "";

    for (var i = 0, l = path.length; i < l; i++) {
        make += path[i] + "/";
        if (!exists(make)) {
            makeDir(make);
        }
    }
}

function saveFile(/**string*/ outDir, /**string*/ fileName, /**string*/ content) {
    fs.writeFileSync(outDir + "/" + fileName, content, "utf8");
}

function exists(/**string*/ path) {
    try {
        fs.statSync(path);
        return true;
    } catch(e) {
        return false;
    }
}

function makeDir(/**string*/ path) {
    fs.mkdirSync(path, 0777);
}

function exportNamespace(namespace) {
    var types = parseNamespace(namespace);
    var path = "docs/api/wrappers/aspnet-mvc/" + namespace;
    var typeName;
    var type;

    makePath(path);

    for (typeName in types) {
        type = types[typeName];
        if (type.methods.length || type.summary) {
            saveFile(path, typeName + ".md", typeToMarkdown(type));
        }
    }
}

exportNamespace("Kendo.Mvc.UI");
exportNamespace("Kendo.Mvc.UI.Fluent");

// vim: ft=javascript
