#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Examples.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sample")]
	public partial class WeatherDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public WeatherDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SampleConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WeatherDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WeatherDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WeatherDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WeatherDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Weather> Weather
		{
			get
			{
				return this.GetTable<Weather>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Weather")]
	public partial class Weather
	{
		
		private int _ID;
		
		private string _Station;
		
		private System.DateTime _Date;
		
		private decimal _TMax;
		
		private decimal _TMin;
		
		private decimal _Wind;
		
		private System.Nullable<decimal> _Gust;
		
		private decimal _Rain;
		
		private System.Nullable<decimal> _Snow;
		
		private string _Events;
		
		public Weather()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Station", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Station
		{
			get
			{
				return this._Station;
			}
			set
			{
				if ((this._Station != value))
				{
					this._Station = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMax", DbType="Decimal(5,2) NOT NULL")]
		public decimal TMax
		{
			get
			{
				return this._TMax;
			}
			set
			{
				if ((this._TMax != value))
				{
					this._TMax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMin", DbType="Decimal(5,2) NOT NULL")]
		public decimal TMin
		{
			get
			{
				return this._TMin;
			}
			set
			{
				if ((this._TMin != value))
				{
					this._TMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wind", DbType="Decimal(5,2) NOT NULL")]
		public decimal Wind
		{
			get
			{
				return this._Wind;
			}
			set
			{
				if ((this._Wind != value))
				{
					this._Wind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gust", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Gust
		{
			get
			{
				return this._Gust;
			}
			set
			{
				if ((this._Gust != value))
				{
					this._Gust = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rain", DbType="Decimal(5,2) NOT NULL")]
		public decimal Rain
		{
			get
			{
				return this._Rain;
			}
			set
			{
				if ((this._Rain != value))
				{
					this._Rain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Snow", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Snow
		{
			get
			{
				return this._Snow;
			}
			set
			{
				if ((this._Snow != value))
				{
					this._Snow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Events", DbType="VarChar(255)")]
		public string Events
		{
			get
			{
				return this._Events;
			}
			set
			{
				if ((this._Events != value))
				{
					this._Events = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
