//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace KendoCRUDService.Models.EF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StockDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StockDataEntities object using the connection string found in the 'StockDataEntities' section of the application configuration file.
        /// </summary>
        public StockDataEntities() : base("name=StockDataEntities", "StockDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockDataEntities object.
        /// </summary>
        public StockDataEntities(string connectionString) : base(connectionString, "StockDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockDataEntities object.
        /// </summary>
        public StockDataEntities(EntityConnection connection) : base(connection, "StockDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Intraday> Intraday
        {
            get
            {
                if ((_Intraday == null))
                {
                    _Intraday = base.CreateObjectSet<Intraday>("Intraday");
                }
                return _Intraday;
            }
        }
        private ObjectSet<Intraday> _Intraday;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Intraday EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIntraday(Intraday intraday)
        {
            base.AddObject("Intraday", intraday);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockDataModel", Name="Intraday")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Intraday : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Intraday object.
        /// </summary>
        /// <param name="symbol">Initial value of the Symbol property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="open">Initial value of the Open property.</param>
        /// <param name="high">Initial value of the High property.</param>
        /// <param name="low">Initial value of the Low property.</param>
        /// <param name="close">Initial value of the Close property.</param>
        /// <param name="volume">Initial value of the Volume property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static Intraday CreateIntraday(global::System.String symbol, global::System.DateTime date, global::System.Decimal open, global::System.Decimal high, global::System.Decimal low, global::System.Decimal close, global::System.Int64 volume, global::System.Int32 id)
        {
            Intraday intraday = new Intraday();
            intraday.Symbol = symbol;
            intraday.Date = date;
            intraday.Open = open;
            intraday.High = high;
            intraday.Low = low;
            intraday.Close = close;
            intraday.Volume = volume;
            intraday.ID = id;
            return intraday;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Symbol
        {
            get
            {
                return _Symbol;
            }
            set
            {
                if (_Symbol != value)
                {
                    OnSymbolChanging(value);
                    ReportPropertyChanging("Symbol");
                    _Symbol = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Symbol");
                    OnSymbolChanged();
                }
            }
        }
        private global::System.String _Symbol;
        partial void OnSymbolChanging(global::System.String value);
        partial void OnSymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Open
        {
            get
            {
                return _Open;
            }
            set
            {
                if (_Open != value)
                {
                    OnOpenChanging(value);
                    ReportPropertyChanging("Open");
                    _Open = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Open");
                    OnOpenChanged();
                }
            }
        }
        private global::System.Decimal _Open;
        partial void OnOpenChanging(global::System.Decimal value);
        partial void OnOpenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal High
        {
            get
            {
                return _High;
            }
            set
            {
                if (_High != value)
                {
                    OnHighChanging(value);
                    ReportPropertyChanging("High");
                    _High = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("High");
                    OnHighChanged();
                }
            }
        }
        private global::System.Decimal _High;
        partial void OnHighChanging(global::System.Decimal value);
        partial void OnHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Low
        {
            get
            {
                return _Low;
            }
            set
            {
                if (_Low != value)
                {
                    OnLowChanging(value);
                    ReportPropertyChanging("Low");
                    _Low = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Low");
                    OnLowChanged();
                }
            }
        }
        private global::System.Decimal _Low;
        partial void OnLowChanging(global::System.Decimal value);
        partial void OnLowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Close
        {
            get
            {
                return _Close;
            }
            set
            {
                if (_Close != value)
                {
                    OnCloseChanging(value);
                    ReportPropertyChanging("Close");
                    _Close = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Close");
                    OnCloseChanged();
                }
            }
        }
        private global::System.Decimal _Close;
        partial void OnCloseChanging(global::System.Decimal value);
        partial void OnCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                if (_Volume != value)
                {
                    OnVolumeChanging(value);
                    ReportPropertyChanging("Volume");
                    _Volume = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Volume");
                    OnVolumeChanged();
                }
            }
        }
        private global::System.Int64 _Volume;
        partial void OnVolumeChanging(global::System.Int64 value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion

    
    }

    #endregion

    
}
