//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kendo.Mvc.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; array cannot be empty..
        /// </summary>
        internal static string ArrayCannotBeEmpty {
            get {
                return ResourceManager.GetString("ArrayCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use InCell edit mode for batch updates..
        /// </summary>
        internal static string BatchUpdatesRequireInCellMode {
            get {
                return ResourceManager.GetString("BatchUpdatesRequireInCellMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Update data binding setting is required for batch updates. Please specify the Update action or url in the DataBinding configuration..
        /// </summary>
        internal static string BatchUpdatesRequireUpdate {
            get {
                return ResourceManager.GetString("BatchUpdatesRequireUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be negative..
        /// </summary>
        internal static string CannotBeNegative {
            get {
                return ResourceManager.GetString("CannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be negative or zero..
        /// </summary>
        internal static string CannotBeNegativeOrZero {
            get {
                return ResourceManager.GetString("CannotBeNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be null..
        /// </summary>
        internal static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be null or empty..
        /// </summary>
        internal static string CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a public property of primitive type to sort by..
        /// </summary>
        internal static string CannotFindPropertyToSortBy {
            get {
                return ResourceManager.GetString("CannotFindPropertyToSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more one column in order when sort mode is set to single column..
        /// </summary>
        internal static string CannotHaveMoreOneColumnInOrderWhenSortModeIsSetToSingleColumn {
            get {
                return ResourceManager.GetString("CannotHaveMoreOneColumnInOrderWhenSortModeIsSetToSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot route to class named &apos;Controller&apos;..
        /// </summary>
        internal static string CannotRouteToClassNamedController {
            get {
                return ResourceManager.GetString("CannotRouteToClassNamedController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set AutoBind if widget is populated during initialization.
        /// </summary>
        internal static string CannotSetAutoBindIfBoundDuringInitialization {
            get {
                return ResourceManager.GetString("CannotSetAutoBindIfBoundDuringInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use Ajax and WebService binding at the same time..
        /// </summary>
        internal static string CannotUseAjaxAndWebServiceAtTheSameTime {
            get {
                return ResourceManager.GetString("CannotUseAjaxAndWebServiceAtTheSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use only server templates in Ajax or WebService binding mode. Please specify a client template as well..
        /// </summary>
        internal static string CannotUseTemplatesInAjaxOrWebService {
            get {
                return ResourceManager.GetString("CannotUseTemplatesInAjaxOrWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use Virtual Scroll with Server binding..
        /// </summary>
        internal static string CannotUseVirtualScrollWithServerBinding {
            get {
                return ResourceManager.GetString("CannotUseVirtualScrollWithServerBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; collection cannot be empty..
        /// </summary>
        internal static string CollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{1}.
        /// </summary>
        internal static string ControllerNameAmbiguousWithoutRouteUrl {
            get {
                return ResourceManager.GetString("ControllerNameAmbiguousWithoutRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request (&apos;{1}&apos;) does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{2}.
        /// </summary>
        internal static string ControllerNameAmbiguousWithRouteUrl {
            get {
                return ResourceManager.GetString("ControllerNameAmbiguousWithRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller name must end with &apos;Controller&apos;..
        /// </summary>
        internal static string ControllerNameMustEndWithController {
            get {
                return ResourceManager.GetString("ControllerNameMustEndWithController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom command routes is available only for server binding..
        /// </summary>
        internal static string CustomCommandRoutesWithAjaxBinding {
            get {
                return ResourceManager.GetString("CustomCommandRoutesWithAjaxBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no DataSource Model Id property specified..
        /// </summary>
        internal static string DataKeysEmpty {
            get {
                return ResourceManager.GetString("DataKeysEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable InLine editing and custom EditorTemplate per column is not supported.
        /// </summary>
        internal static string DataTableInLineEditingWithCustomEditorTemplates {
            get {
                return ResourceManager.GetString("DataTableInLineEditingWithCustomEditorTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify TemplateName when PopUp edit mode is enabled with DataTable binding.
        /// </summary>
        internal static string DataTablePopUpTemplate {
            get {
                return ResourceManager.GetString("DataTablePopUpTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete data binding setting is required by the delete command. Please specify the Delete action or url in the DataBinding configuration..
        /// </summary>
        internal static string DeleteCommandRequiresDelete {
            get {
                return ResourceManager.GetString("DeleteCommandRequiresDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Update data binding setting is required by the edit command. Please specify the Update action or url in the DataBinding configuration..
        /// </summary>
        internal static string EditCommandRequiresUpdate {
            get {
                return ResourceManager.GetString("EditCommandRequiresUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be bigger then {1}..
        /// </summary>
        internal static string FirstPropertyShouldNotBeBiggerThenSecondProperty {
            get {
                return ResourceManager.GetString("FirstPropertyShouldNotBeBiggerThenSecondProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with specified name already exists..
        /// </summary>
        internal static string GroupWithSpecifiedNameAlreadyExists {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with specified name &quot;{0}&quot; already exists. Please specify a different name..
        /// </summary>
        internal static string GroupWithSpecifiedNameAlreadyExistsPleaseSpecifyADifferentName {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameAlreadyExistsPleaseSpecifyADifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with &quot;{0}&quot; does not exist in {1} SharedWebAssets..
        /// </summary>
        internal static string GroupWithSpecifiedNameDoesNotExistInAssetTypeOfSharedWebAssets {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameDoesNotExistInAssetTypeOfSharedWebAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with specified name &quot;{0}&quot; does not exist. Please make sure you have specified a correct name..
        /// </summary>
        internal static string GroupWithSpecifiedNameDoesNotExistPleaseMakeSureYouHaveSpecifiedACorrectName {
            get {
                return ResourceManager.GetString("GroupWithSpecifiedNameDoesNotExistPleaseMakeSureYouHaveSpecifiedACorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InCell editing mode is not supported in server binding mode.
        /// </summary>
        internal static string InCellModeNotSupportedInServerBinding {
            get {
                return ResourceManager.GetString("InCellModeNotSupportedInServerBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InCell editing mode is not supported when ClientRowTemplate is used.
        /// </summary>
        internal static string InCellModeNotSupportedWithRowTemplate {
            get {
                return ResourceManager.GetString("InCellModeNotSupportedWithRowTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided index is out of range..
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert data binding setting is required by the insert command. Please specify the Insert action or url in the DataBinding configuration..
        /// </summary>
        internal static string InsertCommandRequiresInsert {
            get {
                return ResourceManager.GetString("InsertCommandRequiresInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with specified source already exists..
        /// </summary>
        internal static string ItemWithSpecifiedSourceAlreadyExists {
            get {
                return ResourceManager.GetString("ItemWithSpecifiedSourceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local group with name &quot;{0}&quot; already exists..
        /// </summary>
        internal static string LocalGroupWithSpecifiedNameAlreadyExists {
            get {
                return ResourceManager.GetString("LocalGroupWithSpecifiedNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key with the following name &quot;{0}&quot; was not found. Please update all localization files..
        /// </summary>
        internal static string LocalizationKeyNotFound {
            get {
                return ResourceManager.GetString("LocalizationKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound columns require a field or property access expression..
        /// </summary>
        internal static string MemberExpressionRequired {
            get {
                return ResourceManager.GetString("MemberExpressionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be less than {1}..
        /// </summary>
        internal static string MinPropertyMustBeLessThenMaxProperty {
            get {
                return ResourceManager.GetString("MinPropertyMustBeLessThenMaxProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be blank..
        /// </summary>
        internal static string NameCannotBeBlank {
            get {
                return ResourceManager.GetString("NameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot contain spaces..
        /// </summary>
        internal static string NameCannotContainSpaces {
            get {
                return ResourceManager.GetString("NameCannotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;None&quot; is only used for internal purpose..
        /// </summary>
        internal static string NoneIsOnlyUsedForInternalPurpose {
            get {
                return ResourceManager.GetString("NoneIsOnlyUsedForInternalPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one ScriptRegistrar is allowed in a single request..
        /// </summary>
        internal static string OnlyOneScriptRegistrarIsAllowedInASingleRequest {
            get {
                return ResourceManager.GetString("OnlyOneScriptRegistrarIsAllowedInASingleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one StyleSheetRegistrar is allowed in a single request..
        /// </summary>
        internal static string OnlyOneStyleSheetRegistrarIsAllowedInASingleRequest {
            get {
                return ResourceManager.GetString("OnlyOneStyleSheetRegistrarIsAllowedInASingleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only property and field expressions are supported.
        /// </summary>
        internal static string OnlyPropertyAndFieldExpressionsAreSupported {
            get {
                return ResourceManager.GetString("OnlyPropertyAndFieldExpressionsAreSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging must be enabled to use PageOnScroll..
        /// </summary>
        internal static string PagingMustBeEnabledToUsePageOnScroll {
            get {
                return ResourceManager.GetString("PagingMustBeEnabledToUsePageOnScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be bigger then 0..
        /// </summary>
        internal static string PropertyMustBeBiggerThenZero {
            get {
                return ResourceManager.GetString("PropertyMustBeBiggerThenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be positive number..
        /// </summary>
        internal static string PropertyMustBePositiveNumber {
            get {
                return ResourceManager.GetString("PropertyMustBePositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be bigger than {1} and less then {2}.
        /// </summary>
        internal static string PropertyShouldBeInRange {
            get {
                return ResourceManager.GetString("PropertyShouldBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; class is no longer supported. To enable RTL support you must include telerik.rtl.css and apply the &quot;t-rtl&quot; class to a parent HTML element or the &lt;body&gt;..
        /// </summary>
        internal static string Rtl {
            get {
                return ResourceManager.GetString("Rtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolling must be enabled to use PageOnScroll..
        /// </summary>
        internal static string ScrollingMustBeEnabledToUsePageOnScroll {
            get {
                return ResourceManager.GetString("ScrollingMustBeEnabledToUsePageOnScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have SiteMap defined with key &quot;{0}&quot; in ViewData dictionary..
        /// </summary>
        internal static string SiteMapShouldBeDefinedInViewData {
            get {
                return ResourceManager.GetString("SiteMapShouldBeDefinedInViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source must be a virtual path which should starts with &quot;~/&quot;.
        /// </summary>
        internal static string SourceMustBeAVirtualPathWhichShouldStartsWithTileAndSlash {
            get {
                return ResourceManager.GetString("SourceMustBeAVirtualPathWhichShouldStartsWithTileAndSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file does not exist: &quot;{0}&quot;..
        /// </summary>
        internal static string SpecifiedFileDoesNotExist {
            get {
                return ResourceManager.GetString("SpecifiedFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed string cannot be parsed to DateTime object..
        /// </summary>
        internal static string StringNotCorrectDate {
            get {
                return ResourceManager.GetString("StringNotCorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed string cannot be parsed to TimeSpan object..
        /// </summary>
        internal static string StringNotCorrectTimeSpan {
            get {
                return ResourceManager.GetString("StringNotCorrectTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified method is not an action method..
        /// </summary>
        internal static string TheSpecifiedMethodIsNotAnActionMethod {
            get {
                return ResourceManager.GetString("TheSpecifiedMethodIsNotAnActionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time should be bigger than MinTime and less than MaxTime..
        /// </summary>
        internal static string TimeOutOfRange {
            get {
                return ResourceManager.GetString("TimeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should set Tooltip container. Tooltip.For(container).
        /// </summary>
        internal static string TooltipContainerShouldBeSet {
            get {
                return ResourceManager.GetString("TooltipContainerShouldBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set Url and ContentUrl at the same time..
        /// </summary>
        internal static string UrlAndContentUrlCannotBeSet {
            get {
                return ResourceManager.GetString("UrlAndContentUrlCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ValueNotValidForProperty {
            get {
                return ResourceManager.GetString("ValueNotValidForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url of the WebService must be set.
        /// </summary>
        internal static string WebServiceUrlRequired {
            get {
                return ResourceManager.GetString("WebServiceUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add more than once column when sort mode is set to single column..
        /// </summary>
        internal static string YouCannotAddMoreThanOnceColumnWhenSortModeIsSetToSingle {
            get {
                return ResourceManager.GetString("YouCannotAddMoreThanOnceColumnWhenSortModeIsSetToSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use non generic BindTo overload without EnableCustomBinding set to true.
        /// </summary>
        internal static string YouCannotCallBindToWithoutCustomBinding {
            get {
                return ResourceManager.GetString("YouCannotCallBindToWithoutCustomBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot call render more than once..
        /// </summary>
        internal static string YouCannotCallRenderMoreThanOnce {
            get {
                return ResourceManager.GetString("YouCannotCallRenderMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot call Start more than once..
        /// </summary>
        internal static string YouCannotCallStartMoreThanOnce {
            get {
                return ResourceManager.GetString("YouCannotCallStartMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot configure a shared web asset group..
        /// </summary>
        internal static string YouCannotConfigureASharedWebAssetGroup {
            get {
                return ResourceManager.GetString("YouCannotConfigureASharedWebAssetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have to call Start prior calling this method..
        /// </summary>
        internal static string YouMustHaveToCallStartPriorCallingThisMethod {
            get {
                return ResourceManager.GetString("YouMustHaveToCallStartPriorCallingThisMethod", resourceCulture);
            }
        }
    }
}
