//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kendo.Mvc.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add column on the left.
        /// </summary>
        public static string Editor_AddColumnLeft {
            get {
                return ResourceManager.GetString("Editor_AddColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add column on the right.
        /// </summary>
        public static string Editor_AddColumnRight {
            get {
                return ResourceManager.GetString("Editor_AddColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row above.
        /// </summary>
        public static string Editor_AddRowAbove {
            get {
                return ResourceManager.GetString("Editor_AddRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row below.
        /// </summary>
        public static string Editor_AddRowBelow {
            get {
                return ResourceManager.GetString("Editor_AddRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string Editor_BackColor {
            get {
                return ResourceManager.GetString("Editor_BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Editor_Bold {
            get {
                return ResourceManager.GetString("Editor_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert hyperlink.
        /// </summary>
        public static string Editor_CreateLink {
            get {
                return ResourceManager.GetString("Editor_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table.
        /// </summary>
        public static string Editor_CreateTable {
            get {
                return ResourceManager.GetString("Editor_CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete column.
        /// </summary>
        public static string Editor_DeleteColumn {
            get {
                return ResourceManager.GetString("Editor_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string Editor_DeleteFile {
            get {
                return ResourceManager.GetString("Editor_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete row.
        /// </summary>
        public static string Editor_DeleteRow {
            get {
                return ResourceManager.GetString("Editor_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Editor_DialogButtonSeparator {
            get {
                return ResourceManager.GetString("Editor_DialogButtonSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Editor_DialogCancel {
            get {
                return ResourceManager.GetString("Editor_DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Editor_DialogInsert {
            get {
                return ResourceManager.GetString("Editor_DialogInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A directory with this name was not found..
        /// </summary>
        public static string Editor_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Editor_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop files here to upload.
        /// </summary>
        public static string Editor_DropFilesHere {
            get {
                return ResourceManager.GetString("Editor_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Folder.
        /// </summary>
        public static string Editor_EmptyFolder {
            get {
                return ResourceManager.GetString("Editor_EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select font family.
        /// </summary>
        public static string Editor_FontName {
            get {
                return ResourceManager.GetString("Editor_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (inherited font).
        /// </summary>
        public static string Editor_FontNameInherit {
            get {
                return ResourceManager.GetString("Editor_FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select font size.
        /// </summary>
        public static string Editor_FontSize {
            get {
                return ResourceManager.GetString("Editor_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (inherited size).
        /// </summary>
        public static string Editor_FontSizeInherit {
            get {
                return ResourceManager.GetString("Editor_FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Editor_ForeColor {
            get {
                return ResourceManager.GetString("Editor_ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Editor_FormatBlock {
            get {
                return ResourceManager.GetString("Editor_FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate text.
        /// </summary>
        public static string Editor_ImageAltText {
            get {
                return ResourceManager.GetString("Editor_ImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web address.
        /// </summary>
        public static string Editor_ImageWebAddress {
            get {
                return ResourceManager.GetString("Editor_ImageWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        public static string Editor_Indent {
            get {
                return ResourceManager.GetString("Editor_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert HTML.
        /// </summary>
        public static string Editor_InsertHtml {
            get {
                return ResourceManager.GetString("Editor_InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        public static string Editor_InsertImage {
            get {
                return ResourceManager.GetString("Editor_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert ordered list.
        /// </summary>
        public static string Editor_InsertOrderedList {
            get {
                return ResourceManager.GetString("Editor_InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert unordered list.
        /// </summary>
        public static string Editor_InsertUnorderedList {
            get {
                return ResourceManager.GetString("Editor_InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file &quot;{0}&quot; is not valid. Supported file types are {1}..
        /// </summary>
        public static string Editor_InvalidFileType {
            get {
                return ResourceManager.GetString("Editor_InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Editor_Italic {
            get {
                return ResourceManager.GetString("Editor_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center text.
        /// </summary>
        public static string Editor_JustifyCenter {
            get {
                return ResourceManager.GetString("Editor_JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string Editor_JustifyFull {
            get {
                return ResourceManager.GetString("Editor_JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align text left.
        /// </summary>
        public static string Editor_JustifyLeft {
            get {
                return ResourceManager.GetString("Editor_JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align text right.
        /// </summary>
        public static string Editor_JustifyRight {
            get {
                return ResourceManager.GetString("Editor_JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open link in new window.
        /// </summary>
        public static string Editor_LinkOpenInNewWindow {
            get {
                return ResourceManager.GetString("Editor_LinkOpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Editor_LinkText {
            get {
                return ResourceManager.GetString("Editor_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip.
        /// </summary>
        public static string Editor_LinkToolTip {
            get {
                return ResourceManager.GetString("Editor_LinkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web address.
        /// </summary>
        public static string Editor_LinkWebAddress {
            get {
                return ResourceManager.GetString("Editor_LinkWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange by:.
        /// </summary>
        public static string Editor_OrderBy {
            get {
                return ResourceManager.GetString("Editor_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Editor_OrderByName {
            get {
                return ResourceManager.GetString("Editor_OrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Editor_OrderBySize {
            get {
                return ResourceManager.GetString("Editor_OrderBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdent.
        /// </summary>
        public static string Editor_Outdent {
            get {
                return ResourceManager.GetString("Editor_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;A file with name &quot;{0}&quot; already exists in the current directory. Do you want to overwrite it?.
        /// </summary>
        public static string Editor_OverwriteFile {
            get {
                return ResourceManager.GetString("Editor_OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Editor_Search {
            get {
                return ResourceManager.GetString("Editor_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string Editor_Strikethrough {
            get {
                return ResourceManager.GetString("Editor_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Editor_Styles {
            get {
                return ResourceManager.GetString("Editor_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string Editor_Subscript {
            get {
                return ResourceManager.GetString("Editor_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        public static string Editor_Superscript {
            get {
                return ResourceManager.GetString("Editor_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Editor_Underline {
            get {
                return ResourceManager.GetString("Editor_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove hyperlink.
        /// </summary>
        public static string Editor_Unlink {
            get {
                return ResourceManager.GetString("Editor_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Editor_UploadFile {
            get {
                return ResourceManager.GetString("Editor_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string Filter_And {
            get {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Filter_Clear {
            get {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_DateIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is after.
        /// </summary>
        public static string Filter_DateIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is after or equal to.
        /// </summary>
        public static string Filter_DateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is before.
        /// </summary>
        public static string Filter_DateIsLessThan {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is before or equal to.
        /// </summary>
        public static string Filter_DateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_DateIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_EnumIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_EnumIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show items with value that:.
        /// </summary>
        public static string Filter_Info {
            get {
                return ResourceManager.GetString("Filter_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is false.
        /// </summary>
        public static string Filter_IsFalse {
            get {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is true.
        /// </summary>
        public static string Filter_IsTrue {
            get {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_NumberIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        public static string Filter_NumberIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        public static string Filter_NumberIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        public static string Filter_NumberIsLessThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        public static string Filter_NumberIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_NumberIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Filter_Or {
            get {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Select value-.
        /// </summary>
        public static string Filter_SelectValue {
            get {
                return ResourceManager.GetString("Filter_SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Filter_StringContains {
            get {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        public static string Filter_StringDoesNotContain {
            get {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string Filter_StringEndsWith {
            get {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string Filter_StringIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string Filter_StringIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string Filter_StringStartsWith {
            get {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes.
        /// </summary>
        public static string Grid_CancelChanges {
            get {
                return ResourceManager.GetString("Grid_CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Grid_Columns {
            get {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string Grid_Confirmation {
            get {
                return ResourceManager.GetString("Grid_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new record.
        /// </summary>
        public static string Grid_Create {
            get {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Grid_Destroy {
            get {
                return ResourceManager.GetString("Grid_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Grid_SaveChanges {
            get {
                return ResourceManager.GetString("Grid_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Grid_Select {
            get {
                return ResourceManager.GetString("Grid_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        public static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        public static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header and drop it here to group by that column.
        /// </summary>
        public static string Group_Empty {
            get {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} of {2} items.
        /// </summary>
        public static string Pager_Display {
            get {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display.
        /// </summary>
        public static string Pager_Empty {
            get {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the first page.
        /// </summary>
        public static string Pager_First {
            get {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items per page.
        /// </summary>
        public static string Pager_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the last page.
        /// </summary>
        public static string Pager_Last {
            get {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next page.
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the previous page.
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Pager_Refresh {
            get {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all day.
        /// </summary>
        public static string Scheduler_AllDay {
            get {
                return ResourceManager.GetString("Scheduler_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Scheduler_Cancel {
            get {
                return ResourceManager.GetString("Scheduler_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this event?.
        /// </summary>
        public static string Scheduler_Confirmation {
            get {
                return ResourceManager.GetString("Scheduler_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Scheduler_Date {
            get {
                return ResourceManager.GetString("Scheduler_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete event.
        /// </summary>
        public static string Scheduler_DeleteWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_DeleteWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Scheduler_Destroy {
            get {
                return ResourceManager.GetString("Scheduler_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day event.
        /// </summary>
        public static string Scheduler_Editor_AllDayEvent {
            get {
                return ResourceManager.GetString("Scheduler_Editor_AllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Scheduler_Editor_Description {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Scheduler_Editor_EditorTitle {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Scheduler_Editor_End {
            get {
                return ResourceManager.GetString("Scheduler_Editor_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End timezone.
        /// </summary>
        public static string Scheduler_Editor_EndTimezone {
            get {
                return ResourceManager.GetString("Scheduler_Editor_EndTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Scheduler_Editor_Repeat {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use separate start and end time zones.
        /// </summary>
        public static string Scheduler_Editor_SeparateTimezones {
            get {
                return ResourceManager.GetString("Scheduler_Editor_SeparateTimezones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Scheduler_Editor_Start {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timezone.
        /// </summary>
        public static string Scheduler_Editor_StartTimezone {
            get {
                return ResourceManager.GetString("Scheduler_Editor_StartTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Scheduler_Editor_Timezone {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        public static string Scheduler_Editor_TimezoneEditorButton {
            get {
                return ResourceManager.GetString("Scheduler_Editor_TimezoneEditorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezones.
        /// </summary>
        public static string Scheduler_Editor_TimezoneEditorTitle {
            get {
                return ResourceManager.GetString("Scheduler_Editor_TimezoneEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Scheduler_Editor_Title {
            get {
                return ResourceManager.GetString("Scheduler_Editor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Scheduler_Event {
            get {
                return ResourceManager.GetString("Scheduler_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete only this event occurrence or the whole series?.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteRecurring {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current occurrence.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the series.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowSeries {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Recurring Item.
        /// </summary>
        public static string Scheduler_Recurrence_DeleteWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_DeleteWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Daily_Days {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Daily_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every: .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Daily_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Daily_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_EndCountAfter {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_EndCountAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  occurrence(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_EndCountOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_EndCountOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_EndLabel {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_EndNever {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_EndNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_End_EndUntilOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_End_EndUntilOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Daily {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Monthly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Never {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Weekly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Frequencies_Yearly {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Frequencies_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_Day {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  month(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_Months {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every: .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on: .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Monthly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Monthly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_First {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Fourth {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Last {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Second {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        public static string Scheduler_Recurrence_Editor_OffsetPositions_Third {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_OffsetPositions_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every: .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on: .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  week(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Weekly_Weeks {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Weekly_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_Of {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every: .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_RepeatEvery {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_RepeatEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat on: .
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_RepeatOn {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  year(s).
        /// </summary>
        public static string Scheduler_Recurrence_Editor_Yearly_Years {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_Editor_Yearly_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to edit only this event occurrence or the whole series?.
        /// </summary>
        public static string Scheduler_Recurrence_EditRecurring {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current occurrence.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowOccurrence {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the series.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowSeries {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Recurring Item.
        /// </summary>
        public static string Scheduler_Recurrence_EditWindowTitle {
            get {
                return ResourceManager.GetString("Scheduler_Recurrence_EditWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Scheduler_Save {
            get {
                return ResourceManager.GetString("Scheduler_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full day.
        /// </summary>
        public static string Scheduler_ShowFullDay {
            get {
                return ResourceManager.GetString("Scheduler_ShowFullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show business hours.
        /// </summary>
        public static string Scheduler_ShowWorkDay {
            get {
                return ResourceManager.GetString("Scheduler_ShowWorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Scheduler_Time {
            get {
                return ResourceManager.GetString("Scheduler_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Scheduler_Today {
            get {
                return ResourceManager.GetString("Scheduler_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Scheduler_View_Agenda {
            get {
                return ResourceManager.GetString("Scheduler_View_Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Scheduler_View_Day {
            get {
                return ResourceManager.GetString("Scheduler_View_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Scheduler_View_Month {
            get {
                return ResourceManager.GetString("Scheduler_View_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Scheduler_View_Week {
            get {
                return ResourceManager.GetString("Scheduler_View_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Upload_Cancel {
            get {
                return ResourceManager.GetString("Upload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop files here to upload.
        /// </summary>
        public static string Upload_DropFilesHere {
            get {
                return ResourceManager.GetString("Upload_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Upload_Remove {
            get {
                return ResourceManager.GetString("Upload_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Upload_Retry {
            get {
                return ResourceManager.GetString("Upload_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Upload_Select {
            get {
                return ResourceManager.GetString("Upload_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string Upload_StatusFailed {
            get {
                return ResourceManager.GetString("Upload_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded.
        /// </summary>
        public static string Upload_StatusUploaded {
            get {
                return ResourceManager.GetString("Upload_StatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading.
        /// </summary>
        public static string Upload_StatusUploading {
            get {
                return ResourceManager.GetString("Upload_StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        public static string Upload_UploadSelectedFiles {
            get {
                return ResourceManager.GetString("Upload_UploadSelectedFiles", resourceCulture);
            }
        }
    }
}
