#!/bin/bash

xfreerdp $* -d telerik.com \
    --plugin rdpdr --data disk:local:$(dirname $0) -- \
    --app --plugin rail --data "powershell.exe:%systemdrive:\
        -noexit \
        cd \\ ;\
        remove-item '\\chef\\' -recurse -force ;\
        new-item -itemtype directory -path '\\chef\\' ;\
        copy-item '\\\\tsclient\local\*' '\\chef\\' -recurse ;\
        cd chef ;\
        .\\bootstrap.ps1 \
    " -- \
    kendoiis.telerik.com
