#!/bin/bash

# usage: update-windows-slave -u username

xfreerdp $* -d telerik.com \
    --plugin rdpdr --data disk:local:$(dirname $0) -- \
    --app --plugin rail --data "powershell.exe:%systemdrive:\
        cd \\ ;\
        remove-item '\\chef\\' -recurse -force ;\
        new-item -itemtype directory -path '\\chef\\' | out-null;\
        copy-item '\\\\tsclient\local\*' '\\chef\\' -recurse ;\
        cd chef ;\
        .\\bootstrap.ps1 ;\
        chef-solo -c solo.rb -j windows-slave.json ;\
        logoff ;\
    " -- \
    kendoiis.telerik.com
