name: CI | Unit

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  ci-unit:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Setup node cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Lint
        run: gulp jshint

      - name: Build styles
        run: gulp styles

      - name: Build scripts
        run: gulp scripts

      - name: Karma
        run: gulp karma-travis